n_examples: 10000
dataset: cifar10
model_name: Sehwag2021Proxy_R18
threat_model: Linf
batch_size: 4000

criterion_name: targeted_cw
algorithm_name: GD
threat_model: Linf

# Parameters for each attack
param:
  max_iter: 100
  use_cw_value: true
  num_nodes: 10
  epsilon: 0.03137254902
  scale: 1.0
normalization: 
  norm_type: sign
stepsize:
  max_iter: 
  epsilon: 
  strategy: apgd
  initial_stepsize: 0.06274509804
  rho: 0.75
  w_ratio: 0.22
  size_decr_ratio: 0.03
  n_iter_min_ratio: 0.06
algorithm:
  momentum_alpha: 0.75
  beta_method: HS
initialpoint:
  method: input
  epsilon: 
  odi_step: 0.03137254902
  odi_iter: 2
  dataset: 

n_iters_small: 10
additional: true